### ISSUE TITLE
ReferenceError: assignment to undeclared variable indentLevel

### ISSUE THREAD

**Issue by troyvassalotti** [scripting/opmlPackage#12]
In trying to use the `htmlify` option, I'm getting reference errors related to indentLevel and think it's because of this line: https://github.com/scripting/opmlPackage/blob/9c23d26d5c9fb1ee76574f3028de5dcd1f77f433/opmlpackage.js#L135

Specifically the semicolon instead of a comma.

**Comment by scripting** [comment]
You're quite right, while that is legal syntax (surprising to me) it does make `indentLevel` a global variable, which of course was not intended. 

I released an update, hopefully the problem will now be fixed.

Thanks for the report! :-)

**Comment by troyvassalotti** [comment]
Thanks! I upgraded and found one more: https://github.com/scripting/opmlPackage/blob/cc95043f6933acdbf0aece5d836b531bcde93f55/opmlpackage.js#L137 looks like you want `utils.filledString`. I forked it locally and with that change got the resulting HTML list.

**Comment by scripting** [comment]
Thanks for the report. It's pretty clear I never tested that code. ;-)

It's fixed now. Let me know if you encounter any other problems.

**Comment by troyvassalotti** [comment]
Thanks, it works great for me now!
