### ISSUE TITLE
Markdown functions not loaded in node package

### ISSUE THREAD

**Issue by andrewshell** [scripting/opmlPackage#3]
If I install the opml package in a node project and call `opml.markdownToOutline` I get the error:

`ReferenceError: markdownToOutline is not defined`

I can see that `markdownToOutline` and `outlineToMarkdown` are defined in `commoncode.js` but are not exported.

In `opmlpackage.js` I can see that `markdownToOutline` and `outlineToMarkdown` are exported, but not defined.

I suspect a step was missed while exporting to js.

**Comment by scripting** [comment]
@andrewshell -- thanks for the report.

I did not test this part of the release, I was using the code in a JS client app.

I did include commoncode.js in the files part of the [package.json](https://github.com/scripting/opmlPackage/blob/main/package.json) file, I assumed that would cause it to be part of what was installed by NPM. 

Is there something else it needs to do? Hmm.

**Comment by scripting** [comment]
In the docs for package.json, the [files](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#files) section, says:

> The optional files field is an array of file patterns that describes the entries to be included when your package is installed as a dependency.

I have to go out for a bit, but I'll deal with this the first thing when I get back.

**Comment by andrewshell** [comment]
It does seem weird that commoncode.js isn't in what I pulled down from npm. Maybe because it doesn't export any functions?

I also noticed that in commoncode.js you're using functions from daveutils that aren't in that file.  For instance (stringDelete, beginsWith, stringContains, etc)

**Comment by scripting** [comment]
@andrewshell -- I'm going to fix this problem and also writing an example app that reads and writes one of these files. writing some docs too.

**Comment by scripting** [comment]
@andrewshell -- there's a new version released that also includes example code for the new markdown features.

Please let me know if there are any problems. Thanks! :-)

**Comment by andrewshell** [comment]
@scripting It looks like this fixed this issue. I'll create a pull request (just to show a diff) for modifications on converting the structures.
